package com.example.framework.model;

import lombok.*;

/**
 * Response model returned by the API after a user has been stored.
 * This model contains both client-provided fields and server-generated metadata.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class UserRecord {
    /** Unique identifier generated by the server so records can be retrieved later. */
    private long id;
    /** Stored user name echoed back in API responses. */
    private String name;
    /** Stored email value used by tests for equality assertions. */
    private String email;
    /** Stored status value used by tests for workflow verification. */
    private String status;
    /** Timestamp created by the server to show when the record was created. */
    private String createdAt;
}

