package com.example.framework.validation;

import com.example.framework.model.CreateUserRequest;
import com.example.framework.model.UserRecord;
import io.restassured.response.Response;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.testng.Assert;

import java.util.List;

/**
 * Domain-specific validation helper for user API responses.
 * These methods combine transport-level response checks with business assertions for user data.
 * 
 * kept endpoint/domain-specific checks in a dedicated validator like UserResponseValidator
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class UserResponseValidator {

    /**
     * Validates the health endpoint response and asserts the expected status payload.
     */
    public static void validateHealth(Response response) {
        String status = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 200),
                        "schemas/health-response-schema.json"
                )
                .extract()
                .path("status");

        Assert.assertEquals(status, "UP", "Health endpoint should report the API as UP.");
    }

    /**
     * Validates a create-user response and checks that the returned server data matches the request.
     */
    public static UserRecord validateCreatedUser(Response response, CreateUserRequest expectedRequest) {
        UserRecord createdUser = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 201),
                        "schemas/user-response-schema.json"
                )
                .extract()
                .as(UserRecord.class);

        Assert.assertTrue(createdUser.getId() > 0, "Created user id should be generated by the server.");
        Assert.assertEquals(createdUser.getName(), expectedRequest.getName(), "Returned name should match request.");
        Assert.assertEquals(createdUser.getEmail(), expectedRequest.getEmail(), "Returned email should match request.");
        Assert.assertEquals(createdUser.getStatus(), expectedRequest.getStatus(), "Returned status should match request.");
        Assert.assertNotNull(createdUser.getCreatedAt(), "Created timestamp should be present.");
        Assert.assertFalse(createdUser.getCreatedAt().isBlank(), "Created timestamp should not be blank.");

        return createdUser;
    }

    /**
     * Validates a fetch-user response and checks that the returned record matches the expected one.
     */
    public static UserRecord validateFetchedUser(Response response, UserRecord expectedUser) {
        UserRecord fetchedUser = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 200),
                        "schemas/user-response-schema.json"
                )
                .extract()
                .as(UserRecord.class);

        Assert.assertEquals(fetchedUser.getId(), expectedUser.getId(), "Fetched user id should match created user id.");
        Assert.assertEquals(fetchedUser.getName(), expectedUser.getName(), "Fetched name should match.");
        Assert.assertEquals(fetchedUser.getEmail(), expectedUser.getEmail(), "Fetched email should match.");
        Assert.assertEquals(fetchedUser.getStatus(), expectedUser.getStatus(), "Fetched status should match.");

        return fetchedUser;
    }

    /**
     * Validates a list-users response and checks that a specific user id is present in the returned collection.
     */
    public static List<UserRecord> validateUserListContains(Response response, long userId) {
        List<UserRecord> users = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 200),
                        "schemas/user-list-response-schema.json"
                )
                .extract()
                .jsonPath()
                .getList(".", UserRecord.class);

        Assert.assertTrue(
                users.stream().anyMatch(user -> user.getId() == userId),
                "Expected user id " + userId + " to be present in the user list."
        );

        return users;
    }

    /**
     * Validates the delete response and confirms the expected success message is returned.
     */
    public static void validateDeleteSuccess(Response response) {
        String message = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 200),
                        "schemas/message-response-schema.json"
                )
                .extract()
                .path("message");

        Assert.assertEquals(message, "Deleted", "Delete endpoint should confirm deletion.");
    }

    /**
     * Validates the seed response and confirms the requested number of records was created.
     */
    public static List<UserRecord> validateSeededUsers(Response response, int expectedCount) {
        List<UserRecord> seededUsers = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 201),
                        "schemas/user-list-response-schema.json"
                )
                .extract()
                .jsonPath()
                .getList(".", UserRecord.class);

        Assert.assertEquals(seededUsers.size(), expectedCount, "Seed endpoint should create the requested number of users.");
        Assert.assertTrue(
                seededUsers.stream().allMatch(user -> user.getId() > 0),
                "Each seeded user should have a generated id."
        );

        return seededUsers;
    }

    /**
     * Validates an update-user response and checks that returned values match the update request.
     */
    public static UserRecord validateUpdatedUser(Response response, long expectedUserId, CreateUserRequest updateRequest) {
        UserRecord updatedUser = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 200),
                        "schemas/user-response-schema.json"
                )
                .extract()
                .as(UserRecord.class);

        Assert.assertEquals(updatedUser.getId(), expectedUserId, "Updated user id should remain unchanged.");
        Assert.assertEquals(updatedUser.getName(), updateRequest.getName(), "Updated name should match request.");
        Assert.assertEquals(updatedUser.getEmail(), updateRequest.getEmail(), "Updated email should match request.");
        Assert.assertEquals(updatedUser.getStatus(), updateRequest.getStatus(), "Updated status should match request.");
        return updatedUser;
    }

    /**
     * Validates a partial user patch and verifies both changed and unchanged fields after merge.
     */
    public static UserRecord validatePatchedUser(Response response, UserRecord expectedUser) {
        UserRecord patchedUser = ApiSchemaValidator.validateSchema(
                        ApiResponseValidator.validateJsonResponse(response, 200),
                        "schemas/user-response-schema.json"
                )
                .extract()
                .as(UserRecord.class);

        Assert.assertEquals(patchedUser.getId(), expectedUser.getId(), "Patched user id should remain unchanged.");
        Assert.assertEquals(patchedUser.getName(), expectedUser.getName(), "Patched name should reflect the merged result.");
        Assert.assertEquals(patchedUser.getEmail(), expectedUser.getEmail(), "Patched email should reflect the merged result.");
        Assert.assertEquals(patchedUser.getStatus(), expectedUser.getStatus(), "Patched status should reflect the merged result.");
        Assert.assertEquals(patchedUser.getCreatedAt(), expectedUser.getCreatedAt(), "Patched user should preserve the original creation timestamp.");
        return patchedUser;
    }
}
